# Generated by Django 2.2.6 on 2019-11-26 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tblAction',
            fields=[
                ('ActionID', models.AutoField(primary_key=True, serialize=False)),
                ('ActionName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tblAction',
            },
        ),
        migrations.CreateModel(
            name='tblCompany',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyPin', models.CharField(max_length=200)),
                ('CompanyName', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('PhoneNo', models.CharField(max_length=200)),
                ('EmailAddress', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='default.jpg', upload_to='company_pic')),
            ],
            options={
                'db_table': 'tblCompany',
            },
        ),
        migrations.CreateModel(
            name='tblObjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectID', models.IntegerField()),
                ('ActionID', models.IntegerField()),
            ],
            options={
                'db_table': 'tblObjectDetail',
            },
        ),
        migrations.CreateModel(
            name='tblObjectHead',
            fields=[
                ('ObjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ObjectTitle', models.CharField(max_length=200)),
                ('ObjectName', models.CharField(max_length=200)),
                ('ParentID', models.IntegerField()),
                ('IsActive', models.BooleanField(default=True)),
                ('ObjectCategory', models.CharField(max_length=200)),
                ('SerialNo', models.IntegerField()),
                ('Icons', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tblObjectHead',
            },
        ),
        migrations.CreateModel(
            name='tblTransactionLog',
            fields=[
                ('TranID', models.AutoField(primary_key=True, serialize=False)),
                ('ObjectID', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('AccessDateTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('SystemName', models.CharField(max_length=200)),
                ('ActionID', models.IntegerField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'tblTransactionLog',
            },
        ),
        migrations.CreateModel(
            name='tblUserRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectID', models.IntegerField()),
                ('ActionID', models.IntegerField()),
                ('IsAllow', models.BooleanField(default=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblUserRights',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
