# Generated by Django 2.2.6 on 2019-11-07 07:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('account_title', models.CharField(max_length=100, unique=True)),
                ('parent_id', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone_no', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('ntn', models.CharField(max_length=100)),
                ('stn', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemQuantity', models.FloatField()),
                ('unitPrice', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('itemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('narration', models.TextField()),
                ('projectDate', models.DateField(default=datetime.date.today)),
                ('payMethod', models.CharField(max_length=10)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ChartOfAccount')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherHeader',
            fields=[
                ('voucherId', models.AutoField(primary_key=True, serialize=False)),
                ('voucherNo', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('docNo', models.CharField(max_length=100)),
                ('docDate', models.DateField(default=datetime.date.today)),
                ('chequeNo', models.CharField(max_length=100)),
                ('chequeDate', models.DateField(max_length=datetime.date.today)),
                ('description', models.TextField()),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Project')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('invoiceId', models.IntegerField()),
                ('accountId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.ChartOfAccount')),
                ('voucherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.VoucherHeader')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('refrenceId', models.CharField(max_length=100)),
                ('refrenceDate', models.DateField(blank=True)),
                ('tranType', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('refInvTranId', models.IntegerField()),
                ('refInvTranType', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('voucherId', models.CharField(max_length=100)),
                ('accountId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.ChartOfAccount')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('purchaseHeaderId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseNo', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('tax', models.FloatField()),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ChartOfAccount')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Project')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchaseDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseQuantity', models.FloatField()),
                ('purchasePrice', models.FloatField()),
                ('total', models.FloatField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Inventory')),
                ('purchaseHeaderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.PurchaseHeader')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Project'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
