# Generated by Django 2.2.6 on 2019-11-29 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(blank=True, max_length=datetime.date.today, null=True),
        ),
    ]
