# Generated by Django 2.2.6 on 2019-11-29 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_project_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(blank=True, max_length=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
