# Generated by Django 2.2.6 on 2019-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_auto_20191129_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='referenceNo',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
