# Generated by Django 2.2.6 on 2019-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
