# Generated by Django 2.2.6 on 2019-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_transactions_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
