# Generated by Django 2.2.6 on 2019-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_auto_20191121_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
