# Generated by Django 2.2.6 on 2019-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_auto_20191121_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
