# Generated by Django 2.2.6 on 2019-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_auto_20191121_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='itemQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchasePrice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchaseQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchaseheader',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
