# Generated by Django 2.2.6 on 2019-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_auto_20191121_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectCapital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
