# Generated by Django 2.2.6 on 2019-11-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_project_projectcapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectCode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
