# Generated by Django 2.2.6 on 2019-11-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_project_projectcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectCapital',
        ),
    ]
